name: Atualiza 3D Contrib

# agenda: todo dia à meia-noite UTC-3
on:
  schedule:
    - cron: '0 3 * * *'      # 0h no horário de Brasília (UTC-3)
  workflow_dispatch:         # pra você poder rodar manualmente via Actions

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gerar 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@v0.9.0
        with:
          # <— aqui, o token padrão do GitHub Actions,
          # que só consegue ler repositórios PÚBLICOS
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: httpE2Barao
          theme: night-rainbow
          output: profile-3d-contrib

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "ci: atualiza gráfico 3D contrib" || echo "Sem mudanças"
          git push
