name: Atualiza 3D Contrib

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gera gráfico 3D
        uses: yoshi389111/github-profile-3d-contrib@latest   # <-- CORREÇÃO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:     ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "ci: atualiza gráfico 3D contrib" || echo "Sem mudanças"
          git push
